expect error on function with "break" when loop outside function